# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Wobblier"
tagline: ""
description: "Follow <a href=\"https://micro.blog/Wobblier\">@Wobblier on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/Wobblier\">@Wobblier on Micro.blog</a>."
baseurl: ""
url: "https://Wobblier.micro.blog"
markdown: "kramdown"
username: "Wobblier"
microblog_user: "Wobblier"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Wobblier"
name: "Wobblier"
gravatar_hash: "803aa303b41f79446d3d5ef84bb10f1b"
avatar: "https://micro.blog/Wobblier/avatar.jpg"
full_name: "Wobblier"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "4356"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Wobblier"